---
#
# Ansible managed
#
repository:
  description: Check for cve_2021_44228 on your system.
  homepage: https://robertdebock.nl/
  topics: cve202144228, ansible, molecule, tox, playbook, hacktoberfest
