---

- name: check packages
  block:
    - name: get a list of packages
      package_facts:

    - name: check if package is installed
      assert:
        that:
          - item not in ansible_facts.packages
        quiet: yes
      loop: "{{ cve_2021_44228_vulnerable_packages }}"
  rescue:
    - name: show vulnerable package
      debug:
        msg: "Potentially vulneralble: {{ item }}"
      loop: "{{ cve_2021_44228_vulnerable_packages }}"
