---

- name: Check processes
  block:
    - name: Install ps
      ansible.builtin.package:
        name: "{{ cve_2021_44228_ps_package }}"
      notify:
        - Uninstall ps

    - name: Get list of processes
      ansible.builtin.command:
        cmd: ps -ef
      register: cve_2021_44228_processes
      changed_when: no

    - name: Check for java processes
      ansible.builtin.assert:
        that:
          - '"java" not in cve_2021_44228_processes'
        quiet: yes
  rescue:
    - name: Show matched pids
      ansible.builtin.debug:
        msg: "Potentially vulneralble: {{ cve_2021_44228_processes }}"
