---
# handlers file for cve_2021_44228

- name: uninstall ps
  package:
    name: "{{ cve_2021_44228_required_package }}"
    state: absent

- name: uninstall unzip
  package:
    name: unzip
    state: absent
