---
# handlers file for cve_2021_44228

- name: Uninstall ps
  ansible.builtin.package:
    name: "{{ cve_2021_44228_ps_package }}"
    state: absent

- name: Uninstall unzip
  ansible.builtin.package:
    name: unzip
    state: absent
