---
- name: prepare
  hosts: all
  become: yes
  gather_facts: no

  # The role is prepared to install extra software and also remove when
  # the role is done. This is not idempotent, so in this playbook, the
  # required software is already installed.
  vars_files:
    - ../../vars/main.yml

  pre_tasks:
    - name: install required software
      package:
        name: "{{ cve_2021_44228_required_package }}"

  roles:
    - role: robertdebock.bootstrap
